# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'persona_ingreso.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QWidget)

class Ui_vtn_persona_ingreso(object):
    def setupUi(self, vtn_persona_ingreso):
        if not vtn_persona_ingreso.objectName():
            vtn_persona_ingreso.setObjectName(u"vtn_persona_ingreso")
        vtn_persona_ingreso.resize(573, 477)
        self.centralwidget = QWidget(vtn_persona_ingreso)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbl_mensaje = QLabel(self.centralwidget)
        self.lbl_mensaje.setObjectName(u"lbl_mensaje")
        self.lbl_mensaje.setGeometry(QRect(100, 10, 401, 41))
        font = QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.lbl_mensaje.setFont(font)
        self.lbl_mensaje.setAlignment(Qt.AlignCenter)
        self.lbl_nombre1 = QLabel(self.centralwidget)
        self.lbl_nombre1.setObjectName(u"lbl_nombre1")
        self.lbl_nombre1.setGeometry(QRect(70, 70, 131, 20))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.lbl_nombre1.setFont(font1)
        self.lbl_nombre1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_nombre2 = QLabel(self.centralwidget)
        self.lbl_nombre2.setObjectName(u"lbl_nombre2")
        self.lbl_nombre2.setGeometry(QRect(70, 100, 131, 20))
        self.lbl_nombre2.setFont(font1)
        self.lbl_nombre2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_apellido_paterno = QLabel(self.centralwidget)
        self.lbl_apellido_paterno.setObjectName(u"lbl_apellido_paterno")
        self.lbl_apellido_paterno.setGeometry(QRect(70, 130, 131, 20))
        self.lbl_apellido_paterno.setFont(font1)
        self.lbl_apellido_paterno.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_apllido_materno = QLabel(self.centralwidget)
        self.lbl_apllido_materno.setObjectName(u"lbl_apllido_materno")
        self.lbl_apllido_materno.setGeometry(QRect(70, 160, 131, 20))
        self.lbl_apllido_materno.setFont(font1)
        self.lbl_apllido_materno.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_cedula = QLabel(self.centralwidget)
        self.lbl_cedula.setObjectName(u"lbl_cedula")
        self.lbl_cedula.setGeometry(QRect(80, 220, 121, 20))
        self.lbl_cedula.setFont(font1)
        self.lbl_cedula.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_edad = QLabel(self.centralwidget)
        self.lbl_edad.setObjectName(u"lbl_edad")
        self.lbl_edad.setGeometry(QRect(80, 250, 121, 20))
        self.lbl_edad.setFont(font1)
        self.lbl_edad.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_fecha_nacimiento = QLabel(self.centralwidget)
        self.lbl_fecha_nacimiento.setObjectName(u"lbl_fecha_nacimiento")
        self.lbl_fecha_nacimiento.setGeometry(QRect(50, 280, 151, 20))
        self.lbl_fecha_nacimiento.setFont(font1)
        self.lbl_fecha_nacimiento.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_email = QLabel(self.centralwidget)
        self.lbl_email.setObjectName(u"lbl_email")
        self.lbl_email.setGeometry(QRect(66, 310, 131, 20))
        self.lbl_email.setFont(font1)
        self.lbl_email.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_color_preferido = QLabel(self.centralwidget)
        self.lbl_color_preferido.setObjectName(u"lbl_color_preferido")
        self.lbl_color_preferido.setGeometry(QRect(70, 340, 131, 20))
        self.lbl_color_preferido.setFont(font1)
        self.lbl_color_preferido.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.txt_nombre1 = QLineEdit(self.centralwidget)
        self.txt_nombre1.setObjectName(u"txt_nombre1")
        self.txt_nombre1.setGeometry(QRect(210, 70, 261, 20))
        self.txt_nombre1.setMaxLength(50)
        self.txt_nombre2 = QLineEdit(self.centralwidget)
        self.txt_nombre2.setObjectName(u"txt_nombre2")
        self.txt_nombre2.setGeometry(QRect(210, 100, 261, 20))
        self.txt_nombre2.setMaxLength(50)
        self.txt_apellido_paterno = QLineEdit(self.centralwidget)
        self.txt_apellido_paterno.setObjectName(u"txt_apellido_paterno")
        self.txt_apellido_paterno.setGeometry(QRect(210, 130, 261, 20))
        self.txt_apellido_paterno.setMaxLength(50)
        self.txt_apellido_materno = QLineEdit(self.centralwidget)
        self.txt_apellido_materno.setObjectName(u"txt_apellido_materno")
        self.txt_apellido_materno.setGeometry(QRect(210, 160, 261, 20))
        self.txt_apellido_materno.setMaxLength(50)
        self.txt_cedula = QLineEdit(self.centralwidget)
        self.txt_cedula.setObjectName(u"txt_cedula")
        self.txt_cedula.setGeometry(QRect(210, 220, 261, 20))
        self.txt_cedula.setMaxLength(10)
        self.spb_edad = QSpinBox(self.centralwidget)
        self.spb_edad.setObjectName(u"spb_edad")
        self.spb_edad.setGeometry(QRect(210, 250, 111, 22))
        self.date_fecha_nacimiento = QDateEdit(self.centralwidget)
        self.date_fecha_nacimiento.setObjectName(u"date_fecha_nacimiento")
        self.date_fecha_nacimiento.setGeometry(QRect(210, 280, 111, 22))
        self.txt_email = QLineEdit(self.centralwidget)
        self.txt_email.setObjectName(u"txt_email")
        self.txt_email.setGeometry(QRect(210, 310, 261, 20))
        self.txt_email.setMaxLength(100)
        self.cb_color_preferido = QComboBox(self.centralwidget)
        self.cb_color_preferido.addItem("")
        self.cb_color_preferido.addItem("")
        self.cb_color_preferido.addItem("")
        self.cb_color_preferido.addItem("")
        self.cb_color_preferido.addItem("")
        self.cb_color_preferido.addItem("")
        self.cb_color_preferido.addItem("")
        self.cb_color_preferido.setObjectName(u"cb_color_preferido")
        self.cb_color_preferido.setGeometry(QRect(210, 340, 261, 22))
        self.btn_grabar = QPushButton(self.centralwidget)
        self.btn_grabar.setObjectName(u"btn_grabar")
        self.btn_grabar.setGeometry(QRect(160, 400, 75, 23))
        self.btn_limpiar = QPushButton(self.centralwidget)
        self.btn_limpiar.setObjectName(u"btn_limpiar")
        self.btn_limpiar.setGeometry(QRect(360, 400, 75, 23))
        self.lbl_sexo = QLabel(self.centralwidget)
        self.lbl_sexo.setObjectName(u"lbl_sexo")
        self.lbl_sexo.setGeometry(QRect(70, 190, 131, 20))
        self.lbl_sexo.setFont(font1)
        self.lbl_sexo.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cb_sexo = QComboBox(self.centralwidget)
        self.cb_sexo.addItem("")
        self.cb_sexo.addItem("")
        self.cb_sexo.setObjectName(u"cb_sexo")
        self.cb_sexo.setGeometry(QRect(210, 190, 261, 22))
        self.txt_ip = QLineEdit(self.centralwidget)
        self.txt_ip.setObjectName(u"txt_ip")
        self.txt_ip.setGeometry(QRect(210, 370, 261, 20))
        self.txt_ip.setMaxLength(100)
        self.lbl_ip = QLabel(self.centralwidget)
        self.lbl_ip.setObjectName(u"lbl_ip")
        self.lbl_ip.setGeometry(QRect(70, 370, 131, 20))
        self.lbl_ip.setFont(font1)
        self.lbl_ip.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lbl_ob1 = QLabel(self.centralwidget)
        self.lbl_ob1.setObjectName(u"lbl_ob1")
        self.lbl_ob1.setGeometry(QRect(470, 70, 47, 20))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(470, 70, 47, 13))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(470, 130, 47, 13))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(470, 160, 47, 13))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(470, 220, 47, 13))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(470, 310, 47, 13))
        vtn_persona_ingreso.setCentralWidget(self.centralwidget)
        self.mnu_principal = QMenuBar(vtn_persona_ingreso)
        self.mnu_principal.setObjectName(u"mnu_principal")
        self.mnu_principal.setGeometry(QRect(0, 0, 573, 21))
        vtn_persona_ingreso.setMenuBar(self.mnu_principal)
        self.stb_estado = QStatusBar(vtn_persona_ingreso)
        self.stb_estado.setObjectName(u"stb_estado")
        vtn_persona_ingreso.setStatusBar(self.stb_estado)
        QWidget.setTabOrder(self.txt_nombre1, self.txt_nombre2)
        QWidget.setTabOrder(self.txt_nombre2, self.txt_apellido_paterno)
        QWidget.setTabOrder(self.txt_apellido_paterno, self.txt_apellido_materno)
        QWidget.setTabOrder(self.txt_apellido_materno, self.txt_cedula)
        QWidget.setTabOrder(self.txt_cedula, self.spb_edad)
        QWidget.setTabOrder(self.spb_edad, self.date_fecha_nacimiento)
        QWidget.setTabOrder(self.date_fecha_nacimiento, self.txt_email)
        QWidget.setTabOrder(self.txt_email, self.cb_color_preferido)
        QWidget.setTabOrder(self.cb_color_preferido, self.btn_grabar)

        self.retranslateUi(vtn_persona_ingreso)

        QMetaObject.connectSlotsByName(vtn_persona_ingreso)
    # setupUi

    def retranslateUi(self, vtn_persona_ingreso):
        vtn_persona_ingreso.setWindowTitle(QCoreApplication.translate("vtn_persona_ingreso", u"Persona - Ingreso", None))
        self.lbl_mensaje.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Ingreso de Persona", None))
        self.lbl_nombre1.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Primer Nombre:", None))
        self.lbl_nombre2.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Segundo Nombre:", None))
        self.lbl_apellido_paterno.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Apellido Paterno:", None))
        self.lbl_apllido_materno.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Apellido Materno:", None))
        self.lbl_cedula.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Cedula:", None))
        self.lbl_edad.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Edad:", None))
        self.lbl_fecha_nacimiento.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Fecha Nacimiento:", None))
        self.lbl_email.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Email:", None))
        self.lbl_color_preferido.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Color preferido:", None))
        self.txt_nombre1.setText("")
        self.txt_cedula.setText("")
        self.date_fecha_nacimiento.setDisplayFormat(QCoreApplication.translate("vtn_persona_ingreso", u"dd/MM/yyyy", None))
        self.cb_color_preferido.setItemText(0, QCoreApplication.translate("vtn_persona_ingreso", u"Amarillo", None))
        self.cb_color_preferido.setItemText(1, QCoreApplication.translate("vtn_persona_ingreso", u"Azul", None))
        self.cb_color_preferido.setItemText(2, QCoreApplication.translate("vtn_persona_ingreso", u"Violeta", None))
        self.cb_color_preferido.setItemText(3, QCoreApplication.translate("vtn_persona_ingreso", u"Naranja", None))
        self.cb_color_preferido.setItemText(4, QCoreApplication.translate("vtn_persona_ingreso", u"Verde", None))
        self.cb_color_preferido.setItemText(5, QCoreApplication.translate("vtn_persona_ingreso", u"Celeste", None))
        self.cb_color_preferido.setItemText(6, QCoreApplication.translate("vtn_persona_ingreso", u"Rojo", None))

        self.btn_grabar.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Grabar", None))
        self.btn_limpiar.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Limpiar", None))
        self.lbl_sexo.setText(QCoreApplication.translate("vtn_persona_ingreso", u"Sexo:", None))
        self.cb_sexo.setItemText(0, QCoreApplication.translate("vtn_persona_ingreso", u"Hombre", None))
        self.cb_sexo.setItemText(1, QCoreApplication.translate("vtn_persona_ingreso", u"Mujer", None))

        self.lbl_ip.setText(QCoreApplication.translate("vtn_persona_ingreso", u"IP:", None))
        self.lbl_ob1.setText("")
        self.label.setText(QCoreApplication.translate("vtn_persona_ingreso", u"<html><head/><body><p><span style=\" color:#a90000;\">*</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("vtn_persona_ingreso", u"<html><head/><body><p><span style=\" color:#a90000;\">*</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("vtn_persona_ingreso", u"<html><head/><body><p><span style=\" color:#a90000;\">*</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("vtn_persona_ingreso", u"<html><head/><body><p><span style=\" color:#a90000;\">*</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("vtn_persona_ingreso", u"<html><head/><body><p><span style=\" color:#a90000;\">*</span></p></body></html>", None))
    # retranslateUi

